#!/bin/bash

if [[ $# != 1 ]]; then
    echo -n "Usage: $(basename $0) <day number>"
    echo -e "\t(Example: $(basename $0) 1)"
    exit 1
fi

DIRNAME="day_"$1
if [[ -d $DIRNAME ]]; then
    echo "A directory named $DIRNAME already exists"
    exit 1
fi

mkdir $DIRNAME
cd $DIRNAME
touch __init__.py
touch solve.py

cat >solve.py << EOL
"""
Solving Day $1, 2019 Advent of Code Challenge
---
"""

import sys
import os
utils_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.append(utils_path)
from utils import get_input_text, write_solution

if __name__ == "__main__":
    day = $1
    year = 2019
    input_text = get_input_text(day, year)

    ## Part 1 ##
    print(f"Solution Day {day} (Part 1):")

    #  write_solution(day, year,

    ## Part 2 ##
    #  print(f"Solution Day {day} (Part 2):")

    #  write_solution(day, year,

EOL

echo "Day $1 created"
